# Generated by Django 5.2.11 on 2026-02-18 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='liked_recipes',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='disliked_foods',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('goal', 'Goal'), ('fact', 'Fact'), ('event', 'Event'), ('progress', 'Progress')], max_length=50)),
                ('content', models.TextField()),
                ('json_payload', models.TextField()),
                ('importance', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('last_accessed', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset.agent_memory',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meal_planner.meal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity in grams or units')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeFood',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
