# Generated by Django 5.2.11 on 2026-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0002_remove_userpreference_liked_recipes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiendDietParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('servings_per_week', models.PositiveIntegerField()),
            ],
        ),
    ]
