# Generated by Django 5.2.11 on 2026-02-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0003_mienddietparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calories',
            new_name='one_serving_qty',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='qty',
            new_name='serving_unit',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
    ]
